### PR TITLE
fix comment of 'Sublime View - Color' in sublime-settings file

### PR DESCRIPTION
**Pull request by hadisfr**
Ref #59

### CODE REVIEW

**Comment by facelessuser** [comment]
You can ignore the failing error as it is simply related to newer test dependencies since this was last run.

**Comment by hadisfr** [comment]
Oh I didn't see this and tried to remove warning. I can remove last commit if you prefer not to modify lib.

**Comment by facelessuser** [comment]
Yeah, just back out last commit. I'll add an exception instead. The lint plugin like to do things like flag class methods that mirror built-in names, which makes no sense to me. Class methods should be fine. If it was a normal function, I could understand.

**Comment by hadisfr** [comment]
Done.

**Pull request merged**
